[project]
name = "ring-buffer-visual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "fastapi>=0.115.8",
    "flask>=3.1.0",
    "uvicorn>=0.34.0",
]
